[package]
name        = "cw-daemon"
version     = "0.1.0"
authors     = ["Larry Engineer <gm@larry.engineer>"]
edition     = "2021"
description = "Daemon software for the CosmWasm SDK blockchain"
readme      = "./README.md"
homepage    = "https://larry.engineer"
repository  = "https://github.com/steak-enjoyers/cw-sdk"
license     = "AGPL-v3-or-later"
keywords    = ["blockchain", "cosmos", "cosmwasm"]

[dependencies]
cw-sdk = { path = "../sdk" }
structopt = "0.3"
tendermint-abci = "0.25"
tracing-subscriber = "0.2"
